#' Remove from counts tibble any FOV to be excluded
#'
#' Filter data to exclude specific FOV for specific samples
#' 
#' @param dat         counts tibble from countMarkers()
#' @param exclusions  a string of exlusions in the form: Sample1:3+5+9,Sample2:1+16+22
#' @param v           verbose - when set to TRUE, messages
#'                              will be printed to screen as well as to file;
#'                              DEFAULT = TRUE
#' @param debug       print debug messages; default=FALSE
#' @export
remove_exclusions <- function(dat,exclusions,v=TRUE,debug=FALSE){
    exclude_sample_fov <- trimws(unlist(strsplit(exclusions,",")))
    for(ex in exclude_sample_fov){
        samp <- unlist(strsplit(ex,":"))[1]
        fovEx <- unlist(strsplit(ex,":"))[2]
        fovEx <- unlist(strsplit(fovEx,"\\+"))
        if(debug){ logMsg(paste0("Removing ",samp," FOV ",fovEx)) }
        dat <- filter(dat, !(Sample == samp & FOV %in% fovEx))
    }
    return(dat)
}


#' Make a grid of pie charts, one for each given marker showing
#' the percentages of all the marker combinations in which that 
#' positive marker is included
#' 
#' @param   countsTable         tibble of counts generated by countMarkers()
#' @param   markerNames         vector of positive markers, for each of which a pie will be made
#' @param   type                type of chart ["bar"|"pie"]; default="bar"
#' @param   other_threshold     all markers making up less that this percentage will be put togther in 
#'                              a marker combination named 'other'; default=0.05
#' @param   exclude_sample_fov  a string of Sample FOVs to exclude from analysis in the form: 
#'                                  'Sample1:2+4+3,Sample2:1,Sample3:2+4' 
#' @param   pdfFile             output PDF file
#' @param   v                   verbose - when set to TRUE, messages
#'                              will be printed to screen as well as to file;
#'                              DEFAULT = TRUE
#' @param   logFile             file to write log messages to; DEFAULT=NULL
#' @param   debug               print debug messages; DEFAULT=FALSE
#' @export
plot_marker_percentages <- function(countsTable, markerNames, type="bar", other_threshold=0.05, 
                                    exclude_sample_fov=NULL, pdfFile=NULL, v=TRUE, logFile=NULL, 
                                    debug=FALSE){

    ## set up colors
    qual_col_pals <- brewer.pal.info[brewer.pal.info$category == 'qual',]
    col_vector <- unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
    col_vector <- col_vector[-which(col_vector == "#FFFF99")] ## remove ugly yellow
    markerColors <- c()

    if(!is.null(pdfFile)){
        pdf(pdfFile,width=10,height=7)#paper="a4r")
    }

    ## remove median rows from counts table
    countsTable <- filter(countsTable, !is.na(FOV) & !is.na(SLICE))

    ## remove any exclusions
    if(!is.null(exclude_sample_fov)){
        countsTable <- remove_exclusions(countsTable, exclude_sample_fov, v=v, debug=debug)
    }

    for(samp in unique(countsTable$Sample)){
        if(debug){ logMsg(samp,v,logFile,"DEBUG") }

        pieTbl <- tibble()

        for(m in markerNames){
            if(debug){ logMsg(m,v,logFile,"DEBUG") }
            if(length(grep(m,names(countsTable))) == 0){
                #print(paste0("skipping ",m))
                if(debug){ logMsg(paste0("skipping ",m),v,logFile,"DEBUG") }
                next
            }

            tmp <- countsTable

            ## remove marker combos in counts table that do not have this POSITIVE marker
            posMarkerCombos <- names(tmp)[!grepl(paste0(m,"-"),names(tmp))]

            ## get total marker counts and percentage of each marker for this sample
            tmp <- select(tmp, posMarkerCombos) %>%
                 filter(Sample == samp) %>%
                 gather(-(Sample:SLICE), key="Marker", value="Count") %>%
                 group_by(Marker) %>%
                 summarise(TotalMarkerCount = sum(Count)) %>%
                 mutate(PercentAllSampleCells = TotalMarkerCount/sum(TotalMarkerCount))

            ## collapse markers that each make up less than X% of all counts
            other <- filter(tmp, PercentAllSampleCells <= other_threshold) %>%
                       summarise(TotalMarkerCount = sum(TotalMarkerCount),
                                 PercentAllSampleCells = sum(PercentAllSampleCells))
            other$Marker <- "Other"

            ## separate markers that make up more than X% of all counts
            all <- filter(tmp, PercentAllSampleCells > other_threshold) %>%
                     bind_rows(other) %>%
                     arrange(desc(PercentAllSampleCells)) %>%
                     select(-PercentAllSampleCells)  %>%
                     spread(Marker,TotalMarkerCount)

            all$Marker <- m
            all <- select(all, Marker, everything())

            ## add data for this sample to the rest
            pieTbl <- bind_rows(pieTbl, all)

        }

        pie_data <- gather(pieTbl, names(pieTbl)[-1], key="Combo", value="Count") %>%
                    group_by(Marker) %>%
                    mutate(labels=paste0(round((Count/sum(Count,na.rm=TRUE)) * 100, 1),"%")) %>%
                    drop_na()
        ## remove negative markers from the combos for clarity 
        pie_data$Combo <- gsub(",[A-Z]{1,}\\d*-","",pie_data$Combo)

        uniqCombos <- unique(pie_data$Combo)
        if(length(markerColors) == 0){
            markerColors <- col_vector[1:length(uniqCombos)]
            names(markerColors) <- uniqCombos
        } else {
            newCombos <- setdiff(uniqCombos,names(markerColors))
            numExtras = length(setdiff(uniqCombos,names(markerColors)))
            if(numExtras > 0){
                first = length(markerColors)+1
                last = length(markerColors)+numExtras
                extraColors <- col_vector[first:last]
                names(extraColors) <- newCombos
                markerColors <- c(markerColors,extraColors)
            }   
        }

        numRows <- NULL
        if(type == "bar"){ numRows <- 1 }
        p <- ggplot(pie_data, aes(x = factor(1), y = Count, fill=Combo)) +
               facet_wrap(~Marker,nrow = numRows) +
               geom_bar(width=1,stat="identity",position="fill") +
       labs(x = "", y = "", title = paste0(samp,"\n")) +
               scale_fill_manual(values = markerColors) + 
               theme(axis.text.x = element_blank(), 
                     legend.text = element_text(size=8), 
                     legend.key.size = unit(0.5,"cm"),legend.position="bottom") +
               guides(fill=guide_legend(title=""))
        if(type == "pie"){
            p <- p + coord_polar("y")
        }

        print(p)
    }
    if(!is.null(pdfFile)){
        dev.off()
    }
}


